In [52]:
from sklearn.datasets import load_wine
df=load_wine()
df

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [53]:
import pandas as pd
data=pd.DataFrame(df.data,columns=df.feature_names)
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [54]:
data['target']=df.target
data.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0                          3.92   1065.0       0  
1                          3.40   1050.0       0  
2                          3.17   1185.0       0  
3                          3.45   1480.0       0  
4                          2.93    735.0       0

In [55]:
x=data.drop('target',axis=1)
y=data.target

In [56]:
x.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [57]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [59]:
print(f"The size of x_train is {x_train.shape}")
print(f"The size of x_test is {x_test.shape}")
print(f"The size of y_train is {y_train.shape}")
print(f"The size of y_test is {y_test.shape}")

The size of x_train is (142, 13)
The size of x_test is (36, 13)
The size of y_train is (142,)
The size of y_test is (36,)


In [60]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled

array([[ 1.66529275, -0.60840587,  1.21896194, ..., -1.65632857,
        -0.87940904, -0.24860607],
       [-0.54952506,  2.7515415 ,  1.00331502, ..., -0.58463272,
        -1.25462095, -0.72992237],
       [-0.74531007, -1.14354109, -0.93750727, ...,  0.35845962,
         0.2462267 , -0.24860607],
       ...,
       [ 1.714239  , -0.44172441,  0.06884503, ...,  1.04434496,
         0.56585166,  2.69572196],
       [-0.35374006, -0.7399965 , -0.36244882, ...,  0.01551695,
        -0.74044166, -0.79631083],
       [-0.78201975,  0.06709269,  0.35637426, ..., -0.67036839,
         1.09392769, -0.98551793]])

In [61]:
x_test_scaled=scaler.transform(x_test)
x_test_scaled

array([[ 8.08733375e-01,  6.37318741e-01,  7.15785791e-01,
        -1.24128036e+00,  1.06556722e+00,  6.46636689e-01,
         1.02724237e+00, -1.54932094e+00,  8.93605295e-02,
         1.82522280e-02,  1.55169482e-02,  1.06613421e+00,
         3.65487151e-01],
       [ 1.50621744e+00,  1.46195334e+00,  2.84491948e-01,
        -1.66513218e-01,  7.23080697e-01,  8.82684015e-01,
         6.47480801e-01, -5.32234717e-01, -6.15594759e-01,
         7.85270273e-02, -3.70293555e-01,  1.02444400e+00,
         1.14555151e+00],
       [-6.00625639e-02,  3.82910194e-01,  1.21896194e+00,
         4.43489751e-01, -3.04378866e-01, -1.17879597e+00,
        -1.50117016e+00,  1.26722552e+00, -1.47529633e+00,
        -1.97014913e-01, -7.98971892e-01, -3.93023224e-01,
        -4.47771435e-01],
       [ 9.18862438e-01, -7.66314624e-01,  1.21896194e+00,
         8.79206158e-01,  3.81076551e-02,  1.11873134e+00,
         1.24710433e+00, -6.10472119e-01,  1.32733079e+00,
         2.76572797e-01,  1.00147712e

In [62]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [63]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,x_train_scaled,y_train,cv=5)
scores

array([0.91903106, 0.83400984, 0.91944182, 0.87369216, 0.80268562])

In [64]:
import numpy as np
np.mean(scores)

np.float64(0.8697720988347237)

In [65]:
y_pred=model.predict(x_test_scaled)
y_pred

array([ 0.16948139,  0.30709157,  1.49198553,  0.22588624,  0.93222953,
        0.12650909,  0.96078189,  1.93693631,  0.47339083,  1.40225522,
        0.15100309,  1.9790992 ,  0.43528987,  1.37195655,  0.14464495,
        1.09944851,  1.2347296 ,  1.05378116,  0.11646181,  0.94668303,
       -0.33225133,  0.56512868,  1.159081  ,  2.05378099,  2.20616725,
        2.02943242,  1.02403472,  0.74380649,  1.0818711 ,  0.4925743 ,
        0.15389578,  1.06019151,  1.61713469,  0.07722681,  0.02678845,
       -0.22555325])

In [66]:
from sklearn.metrics import r2_score
score=r2_score(y_pred,y_test)

In [67]:
score

0.8570395563565777

In [68]:
print(f"The accuracy is {score*100}")

The accuracy is 85.70395563565776


Ridge Regression

In [69]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV

In [70]:
ridge_regression=Ridge()

In [71]:
para={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90,100]}
ridge_cv=GridSearchCV(ridge_regression,para,cv=5)

In [72]:
ridge_cv

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90,
                                   100]})

In [73]:
ridge_cv.fit(x_train_scaled,y_train)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90,
                                   100]})

In [74]:
y_pred_ridge=ridge_cv.predict(x_test_scaled)

In [75]:
pred=r2_score(y_pred_ridge,y_test)

In [76]:
pred

0.8517275472186834

In [77]:
print(f"The accuracy is {pred*100}")

The accuracy is 85.17275472186834


Lasso Regression

In [78]:
from sklearn.linear_model import Lasso

In [79]:
para={'alpha':[1,2,5,10,20,30,40,50,60,70,80,90,100]}
lasso_cv=GridSearchCV(Lasso(),para,cv=5)

In [80]:
lasso_cv

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90,
                                   100]})

In [81]:
lasso_cv.fit(x_train_scaled,y_train)

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1, 2, 5, 10, 20, 30, 40, 50, 60, 70, 80, 90,
                                   100]})

In [82]:
y_pred_lasso=lasso_cv.predict(x_test_scaled)

In [83]:
pres=r2_score(y_pred_lasso,y_test)

In [84]:
pres

-1.2181896226328664e+31

In [85]:
print(f"The accuracy is {pres*100}")

The accuracy is -1.2181896226328664e+33
